---
all:
  children:
    post_cluster:
       hosts:
         host1:
           ansible_host: "192.168.56.205"
           ansible_private_key_file: ".vagrant/machines/postgres1/virtualbox/private_key"
         host2:
           ansible_host: "192.168.56.206"
           ansible_private_key_file: ".vagrant/machines/postgres2/virtualbox/private_key"        
         host3:
           ansible_host: "192.168.56.207"
           ansible_private_key_file: ".vagrant/machines/postgres3/virtualbox/private_key"
    haproxy:
      hosts:
        haproxy_postgres:
          ansible_host: "192.168.56.208"
          ansible_private_key_file: ".vagrant/machines/haproxy/virtualbox/private_key"
    backend:
      hosts:
        backend1:
          ansible_host: "192.168.56.209"
          ansible_private_key_file: ".vagrant/machines/backend1/virtualbox/private_key"
        backend2:
          ansible_host: "192.168.56.210"
          ansible_private_key_file: ".vagrant/machines/backend2/virtualbox/private_key"
    data:
      hosts:
        gluster1:
          ansible_host: "192.168.56.199"
          ansible_private_key_file: ".vagrant/machines/gluster1/virtualbox/private_key"
        gluster2:
          ansible_host: "192.168.56.200"
          ansible_private_key_file: ".vagrant/machines/gluster2/virtualbox/private_key"
        gluster3:
          ansible_host: "192.168.56.201"
          ansible_private_key_file: ".vagrant/machines/gluster3/virtualbox/private_key"
    consul_srv:
      hosts:
        consul1:
          ansible_host: "192.168.56.202"
          ansible_private_key_file: ".vagrant/machines/consul1/virtualbox/private_key"
        consul2:
          ansible_host: "192.168.56.203"
          ansible_private_key_file: ".vagrant/machines/consul2/virtualbox/private_key"
        consul3:
          ansible_host: "192.168.56.204"
          ansible_private_key_file: ".vagrant/machines/consul3/virtualbox/private_key"
    frontend:
      hosts:
        haproxy_front:
          ansible_host: "192.168.56.212"
          ansible_private_key_file: ".vagrant/machines/haproxy-front1/virtualbox/private_key"
    monitring:
      hosts:
        grafana:
          ansible_host: "192.168.56.213"
          ansible_private_key_file: ".vagrant/machines/grafana/virtualbox/private_key"
  vars:
    consul_key: "8KgdZ9K58nqZwBfzvJqwb6EcyiyHHX5WCjCLA5jDngE="

          

  
  
          

...
