- name: install some packets
  command: sudo yum install wget gcc-c++ openssl-devel pcre-static pcre-devel systemd-devel -y
- name: download latest haproxy
  unarchive:
    src: http://www.haproxy.org/download/2.9/src/haproxy-2.9.4.tar.gz
    dest: /usr/bin/
    remote_src: true
- name: prepare make env
  command: make TARGET=linux-glibc USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_CRYPT_H=1 USE_LIBCRYPT=1 USE_SYSTEMD=1
  args:
    chdir: /usr/bin/haproxy-2.9.4/
- name: create dir haproxy
  file:
    path: /etc/haproxy/
    state: directory
- name: make install haproxy
  command: make install
  args:
    chdir: /usr/bin/haproxy-2.9.4/
- name: create systemd unit file
  copy:
    content: |
      [Unit]
      Description=HAProxy Load Balancer
      After=syslog.target network.target
      [Service]
      Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/run/haproxy.pid"
      ExecStartPre=/usr/local/sbin/haproxy -f $CONFIG -c -q
      ExecStart=/usr/local/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE
      ExecReload=/usr/local/sbin/haproxy -f $CONFIG -c -q
      ExecReload=/bin/kill -USR2 $MAINPID
      KillMode=mixed
      Restart=always
      SuccessExitStatus=143
      Type=notify
      [Install]
      WantedBy=multi-user.target
    dest: /usr/lib/systemd/system/haproxy.service
- name: config haproxy
  copy:
    content: |
      defaults
          timeout connect 5s
          timeout client 1m
          timeout server 1m

      frontend stats
          bind *:1936
          mode http
          stats uri /
          stats show-legends
          no log

      frontend http_front
          bind *:80
          default_backend http_back

      backend http_back
          balance roundrobin
          server-template wiki 1-2 _wiki._tcp.service.consul resolvers consul    resolve-opts allow-dup-ip resolve-prefer ipv4 check

      resolvers consul
          nameserver consul 192.168.56.202:8600
          accepted_payload_size 8192
          hold valid 5s
    dest: /etc/haproxy/haproxy.cfg
- name: start haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: true